### ISSUE TITLE
Is this still working ?

### ISSUE THREAD

**Issue by ghost** [zerratar/CrunchyrollAPI#2]
This seems fairly old, do you know if this is still working and if not do you know any Up2Date C# Alternative ?

**Comment by zerratar** [comment]
I havnt tested this in years. I can give it a spin and see if it works but I kinda doubt it. They must have made a gazillion updates to their API's since back then. But I could eventually look into updating it if its possible.

**Comment by ghost** [comment]
Yeah that would be nice if you could look if it still works and if not, if you can update it.

**Comment by ghost** [comment]
Hey i will do everyone a favor and upgrade it to .NET 5 and work out any changes the api had.
